"""Fixed-step engine that runs without a server and without real-time waits."""

from collections import deque
from random import Random

from bflow.core.checks import check_quantity
from bflow.core.events import EventLog, Severity
from bflow.core.layout import LayoutConfig, minimal_layout
from bflow.core.models import Baggage, Conveyor
from bflow.core.stats import BeltStats, InputStats, OutputStats, Stats


STEP_MS = 50
STEP_SECONDS = STEP_MS / 1000
# Throughput counts the correct deliveries of the last 60 simulated seconds.
THROUGHPUT_WINDOW_TICKS = 60 * 1000 // STEP_MS


class Engine:
    """Owns the layout, state and random generator of a single run.

    The tick counts completed steps: the initial state is at tick 0, time 0.
    Each call to step() completes exactly 50 simulated ms. The caller decides
    when to run it: pause and real-time speed do not change the step.
    Time is derived from the integer tick, avoiding errors from repeatedly
    adding 0.05.

    All random draws in the engine use rng, never the global generator of the
    random module: the same seed and the same operations reproduce the run
    with no interference between instances. Without a layout the engine runs
    the one-belt minimal route.
    """

    def __init__(self, layout: LayoutConfig | None = None, *, seed: int = 42) -> None:
        if isinstance(seed, bool) or not isinstance(seed, int):
            raise ValueError("seed must be an integer")
        self.layout = layout if layout is not None else minimal_layout()
        self.seed = seed
        self.rng = Random(seed)
        self._tick = 0
        # One state per belt, in layout order.
        self.conveyors = {belt.id: Conveyor(belt) for belt in self.layout.belts}
        # Most bags each belt can hold: n bags need n lengths and n - 1 gaps.
        # The tiny margin keeps an exact fit from being lost to rounding.
        bag, gap = self.layout.baggage_length_m, self.layout.min_gap_m
        self.belt_capacities = {belt.id: int((belt.length_m + gap) / (bag + gap) + 1e-9)
                                for belt in self.layout.belts}
        # Belt fed by each input: the layout guarantees exactly one.
        self.input_conveyors = {belt.source_id: self.conveyors[belt.id]
                                for belt in self.layout.belts
                                if belt.source_id in {node.id for node in self.layout.inputs}}
        self._output_ids = [node.id for node in self.layout.outputs]
        # Belts entering each merge, in layout order: the order of the turns.
        self.merge_inputs = {node.id: [belt.id for belt in self.layout.belts
                                       if belt.target_id == node.id]
                             for node in self.layout.merges}
        # The belt each belt hands its bags to: the following belt, or the
        # belt leaving the merge it ends at. Belts ending at an output or a
        # sorter are not here (see _next_conveyor).
        self._next_conveyors = {}
        for belt in self.layout.belts:
            if belt.target_id in self.conveyors:
                self._next_conveyors[belt.id] = self.conveyors[belt.target_id]
            # Not elif: a belt leaving a merge may also turn a corner.
            if belt.source_id in self.merge_inputs:
                for belt_id in self.merge_inputs[belt.source_id]:
                    self._next_conveyors[belt_id] = self.conveyors[belt.id]
        # Belt whose bag each merge let through last; None before the first.
        self.last_merged: dict[str, str | None] = {node.id: None for node in self.layout.merges}
        # For each sorter, the branch leading to each output after it: the
        # layout allows one route per output, so the choice is predetermined.
        self.sorter_routes = {node.id: {output_id: belt.id
                                        for belt in self.layout.belts
                                        if belt.source_id == node.id
                                        for output_id in self._outputs_after(belt.id)}
                              for node in self.layout.sorters}
        # Bags generated but not yet admitted, per input, oldest first.
        self.waiting: dict[str, deque[Baggage]] = {node.id: deque() for node in self.layout.inputs}
        self.generated_count = 0
        self.generated_by_input = {node.id: 0 for node in self.layout.inputs}
        # Current rate of each input: the layout's, until the operator changes
        # it. Arrivals are counted from the tick of the last change and the
        # bags generated by then (see _generate).
        self.arrival_rates = {node.id: node.arrival_rate_bags_s for node in self.layout.inputs}
        self._rate_since = {node.id: (0, 0) for node in self.layout.inputs}
        self.admitted_count = 0
        self.correctly_delivered_count = 0
        self.misdelivered_count = 0
        # Arrivals at each output, split into correct and wrong.
        self.correctly_delivered_by_output = {node.id: 0 for node in self.layout.outputs}
        self.misdelivered_by_output = {node.id: 0 for node in self.layout.outputs}
        self._total_travel_time_s = 0.0
        # Ticks of the correct deliveries still inside the throughput window,
        # oldest first: bounded by what the plant can deliver in 60 s.
        self._recent_delivery_ticks: deque[int] = deque()
        # Only the exits of the last tick: no unbounded history.
        self.exited_this_tick: tuple[Baggage, ...] = ()
        # Wrong sorting: the chance that a sorter sends a bag down a wrong
        # branch, and an operator's request to force it on the next bag.
        self.missort_probability = 0.0
        self.missort_forced = False
        self.events = EventLog()
        self._entrance_queued = {node.id: False for node in self.layout.inputs}

    @property
    def tick(self) -> int:
        """Number of completed steps, initially zero."""
        return self._tick

    @property
    def time_s(self) -> float:
        """Simulated time in seconds, computed without accumulating rounding errors."""
        return self._tick * STEP_MS / 1000

    @property
    def waiting_count(self) -> int:
        """Bags waiting at all the inputs."""
        return sum(len(queue) for queue in self.waiting.values())

    @property
    def exited_count(self) -> int:
        """All exits, correct and wrong, without a duplicate counter."""
        return self.correctly_delivered_count + self.misdelivered_count

    @property
    def in_transit_count(self) -> int:
        """Bags on any belt, including stopped ones; waiting bags excluded."""
        return sum(len(conveyor.baggage) for conveyor in self.conveyors.values())

    @property
    def mean_travel_time_s(self) -> float | None:
        """Mean admission → exit time, wrong exits included; None without samples.

        CLI and GUI display None as "—". Only the sum of the times is kept,
        not a growing history of exited bags.
        """
        if self.exited_count == 0:
            return None
        return self._total_travel_time_s / self.exited_count

    @property
    def throughput(self) -> int:
        """Correct deliveries in the last 60 simulated seconds, this tick included."""
        return len(self._recent_delivery_ticks)

    def stats(self) -> Stats:
        """Snapshot of the counters at the current tick, for the CLI and GUI."""
        return Stats(
            tick=self.tick,
            time_s=self.time_s,
            generated=self.generated_count,
            waiting=self.waiting_count,
            admitted=self.admitted_count,
            correctly_delivered=self.correctly_delivered_count,
            misdelivered=self.misdelivered_count,
            in_transit=self.in_transit_count,
            mean_travel_time_s=self.mean_travel_time_s,
            errors=self.events.counts[Severity.ERROR],
            warnings=self.events.counts[Severity.WARNING],
            throughput=self.throughput,
            belts=tuple(BeltStats(belt_id, len(conveyor.baggage), self.belt_capacities[belt_id])
                        for belt_id, conveyor in self.conveyors.items()),
            inputs=tuple(InputStats(input_id, len(queue))
                         for input_id, queue in self.waiting.items()),
            outputs=tuple(OutputStats(output_id, self.correctly_delivered_by_output[output_id],
                                      self.misdelivered_by_output[output_id])
                          for output_id in self._output_ids),
        )

    def stop_belt(self, belt_id: str) -> None:
        """Stops one belt on the operator's command, from the next step.

        Its bags stay where they are and the queue grows upstream; the rest
        of the plant keeps running. Stopping a stopped belt does nothing.
        """
        self._set_stopped(belt_id, True)

    def restart_belt(self, belt_id: str) -> None:
        """Restarts a belt stopped by the operator, from the next step."""
        self._set_stopped(belt_id, False)

    def _set_stopped(self, belt_id: str, stopped: bool) -> None:
        """Changes a belt's local stop, recording an event only if it changes.

        It never touches a fault: restarting a faulty belt leaves it halted.
        """
        conveyor = self._conveyor(belt_id)
        if conveyor.stopped == stopped:
            return
        conveyor.stopped = stopped
        if stopped:
            kind, message = "belt_stopped", "Belt stopped by the operator"
        else:
            kind, message = "belt_restarted", "Belt restarted by the operator"
        # A voluntary stop is information, not a fault.
        self.events.record(self.tick, self.time_s, Severity.INFO, kind, message,
                           element_id=belt_id)

    def fault_belt(self, belt_id: str) -> None:
        """Puts one belt in fault, from the next step, until it is repaired.

        The belt halts like a stopped one, but restart_belt does not clear the
        fault: only repair_belt does. The operator's stop is independent, so a
        belt stopped during the fault stays stopped after the repair. Records
        an error event when the fault starts; a fault on a faulty belt does
        nothing.
        """
        conveyor = self._conveyor(belt_id)
        if conveyor.faulty:
            return
        conveyor.faulty = True
        self.events.record(self.tick, self.time_s, Severity.ERROR, "belt_fault",
                           "Belt fault: halted until repaired", element_id=belt_id)

    def repair_belt(self, belt_id: str) -> None:
        """Repairs a faulty belt, from the next step; does nothing on a working one.

        The belt moves again unless the operator also stopped it. The repair
        is information: it resolves the fault without counting a new error.
        """
        conveyor = self._conveyor(belt_id)
        if not conveyor.faulty:
            return
        conveyor.faulty = False
        self.events.record(self.tick, self.time_s, Severity.INFO, "belt_repaired",
                           "Belt repaired", element_id=belt_id)

    def _conveyor(self, belt_id: str) -> Conveyor:
        if belt_id not in self.conveyors:
            raise ValueError(f"Unknown belt: {belt_id!r}")
        return self.conveyors[belt_id]

    def set_arrival_rate(self, input_id: str, rate_bags_s: float) -> None:
        """Changes one input's rate on the operator's command, from the next step.

        The next arrival comes a full interval of the new rate after the
        change; bags already waiting stay in the queue. Setting the same rate
        does nothing. Records an info event when the rate changes.
        """
        if input_id not in self.arrival_rates:
            raise ValueError(f"Unknown input: {input_id!r}")
        check_quantity("rate_bags_s", rate_bags_s)
        if self.arrival_rates[input_id] == rate_bags_s:
            return
        self.arrival_rates[input_id] = rate_bags_s
        self._rate_since[input_id] = (self.tick, self.generated_by_input[input_id])
        self.events.record(self.tick, self.time_s, Severity.INFO, "input_rate_changed",
                           f"Arrival rate set to {rate_bags_s:g} bags/s", element_id=input_id)

    def set_missort_probability(self, probability: float) -> None:
        """Sets the chance of a wrong sorting at each sorter passage, from the next step.

        Zero (the initial value) makes no random draw, so a run without
        errors is the same as before they existed. Records an info event
        when the value changes.
        """
        check_quantity("probability", probability)
        if probability > 1:
            raise ValueError("probability must be at most 1")
        if probability == self.missort_probability:
            return
        self.missort_probability = probability
        self.events.record(self.tick, self.time_s, Severity.INFO, "missort_probability_changed",
                           f"Wrong sorting probability set to {probability:g}")

    def force_missort(self) -> None:
        """Makes the next bag decided at any sorter take a wrong branch.

        Asking again before that bag arrives does nothing: one request, one
        error. Records an info event for the request.
        """
        if self.missort_forced:
            return
        self.missort_forced = True
        self.events.record(self.tick, self.time_s, Severity.INFO, "missort_forced",
                           "Wrong sorting forced on the next bag")

    def step(self) -> None:
        """Completes one fixed step without reading real time or waiting."""
        self._tick += 1
        self._move()
        self._sort()
        leaving = self._resolve_merges(self._evaluate_transfers())
        self._apply_transfers(leaving)
        self._forget_old_deliveries()
        self._generate()
        self._admit()
        self._update_entrance_queues()

    def _move(self) -> None:
        """Advances each running belt from the exit towards the entrance.

        On each belt the front edge stops at the end of the belt or at the
        minimum gap from the rear edge of the bag ahead, using its updated
        position. Ready bags are moved to the next element only after every
        bag has finished moving.
        """
        for conveyor in self.conveyors.values():
            if conveyor.halted:
                continue
            distance = conveyor.config.speed_m_s * STEP_SECONDS
            front_limit = conveyor.config.length_m
            for baggage in reversed(conveyor.baggage):
                max_position = front_limit - baggage.length_m
                # max prevents tiny backward moves caused by rounding of the gap.
                baggage.position_m = max(
                    baggage.position_m,
                    min(baggage.position_m + distance, max_position),
                )
                front_limit = baggage.position_m - self.layout.min_gap_m

    def _outputs_after(self, element_id: str) -> set[str]:
        """The outputs a bag can reach from a belt or node, following the targets.

        The layout has no cycles, so the recursion always ends at outputs.
        """
        if element_id in self._output_ids:
            return {element_id}
        if element_id in self.conveyors:
            return self._outputs_after(self.conveyors[element_id].config.target_id)
        # A merge or sorter: the outputs after every belt leaving it.
        return set().union(*(self._outputs_after(belt.id) for belt in self.layout.belts
                             if belt.source_id == element_id))

    def _next_conveyor(self, conveyor: Conveyor, baggage: Baggage) -> Conveyor | None:
        """The belt that receives the front bag of a belt; None when it ends at an output.

        After a sorter it is the branch leading to the bag's route output:
        its destination, or the wrong output a sorting error chose.
        """
        target_id = conveyor.config.target_id
        if target_id in self.sorter_routes:
            return self.conveyors[self.sorter_routes[target_id][baggage.route_output_id]]
        return self._next_conveyors.get(conveyor.config.id)

    def _sort(self) -> None:
        """Decides, once per passage, whether each sorter makes a sorting error.

        A sorter decides for the front bag of the belt entering it as soon
        as the bag's front edge reaches the end, whether or not its branch
        has space; a bag waiting there is not decided again. A forced error
        takes the first decided bag; otherwise the error happens with the
        set probability (no draw at zero). A bag already missorted is not
        decided again: it heads for its wrong output, with no second error.
        """
        for conveyor in self.conveyors.values():
            sorter_id = conveyor.config.target_id
            if sorter_id not in self.sorter_routes or not conveyor.baggage:
                continue
            baggage = conveyor.baggage[-1]
            if (baggage.sorted_at_id == sorter_id
                    or baggage.position_m < conveyor.config.length_m - baggage.length_m):
                continue
            baggage.sorted_at_id = sorter_id
            if baggage.missorted_to_id is not None:
                continue
            if self.missort_forced:
                self.missort_forced = False
            elif (self.missort_probability == 0
                  or self.rng.random() >= self.missort_probability):
                continue
            self._missort(baggage, sorter_id)

    def _missort(self, baggage: Baggage, sorter_id: str) -> None:
        """Sends the bag down a wrong branch, towards an output it does not belong to.

        The branch is drawn among the sorter's other branches, then the
        output among those after it, in layout order. This is the error
        event; the arrival at the wrong output is classified, not counted
        again.
        """
        right = self.sorter_routes[sorter_id][baggage.destination_id]
        wrong = [belt.id for belt in self.layout.belts
                 if belt.source_id == sorter_id and belt.id != right]
        branch_id = self.rng.choice(wrong)
        after = self._outputs_after(branch_id)
        baggage.missorted_to_id = self.rng.choice([output_id for output_id in self._output_ids
                                                   if output_id in after])
        self.events.record(self.tick, self.time_s, Severity.ERROR, "wrong_sorting",
                           f"Wrong sorting: sent down {branch_id} instead of towards "
                           f"{baggage.destination_id}",
                           element_id=sorter_id, baggage_id=baggage.id)

    def _has_entry_space(self, conveyor: Conveyor, baggage: Baggage) -> bool:
        """True if the bag fits at position zero, keeping the gap to the nearest bag."""
        if not conveyor.baggage:
            return True
        return conveyor.baggage[0].position_m >= baggage.length_m + self.layout.min_gap_m

    def _evaluate_transfers(self) -> tuple[Conveyor, ...]:
        """Returns the belts whose front bag is ready to leave, without mutating state.

        A bag is ready when its front edge is at the end of the belt. The
        limit uses the same subtraction as movement, avoiding inconsistent
        comparisons due to rounding; no epsilon brings the exit forward.
        An output always accepts the bag. The next belt (the following one,
        the one leaving a merge, or the branch of the bag's destination after
        a sorter) accepts it only if its entrance has space; otherwise the bag
        waits at the end of its belt, and the bags behind it wait too. Several
        belts can be ready for the same merge: _resolve_merges chooses one.
        A halted belt (stopped or faulty) hands over nothing, but can still
        receive a bag.
        """
        leaving = []
        for conveyor in self.conveyors.values():
            if conveyor.halted or not conveyor.baggage:
                continue
            baggage = conveyor.baggage[-1]
            if baggage.position_m < conveyor.config.length_m - baggage.length_m:
                continue
            next_conveyor = self._next_conveyor(conveyor, baggage)
            if next_conveyor is None or self._has_entry_space(next_conveyor, baggage):
                leaving.append(conveyor)
        return tuple(leaving)

    def _resolve_merges(self, ready: tuple[Conveyor, ...]) -> tuple[Conveyor, ...]:
        """Lets at most one bag per tick through each merge, taking turns; no mutation.

        Only one bag fits at the entrance of the belt leaving the merge, so
        the others wait. The turn goes to the first ready belt after the one
        let through last, in layout order and wrapping around: with bags
        waiting on every belt they pass one each in turn, and a belt that is
        the only one ready never waits for the others. Before the first bag
        the turn starts from the first belt. Belts not ending at a merge are
        kept as they are, in the same order.
        """
        ready_ids = {conveyor.config.id for conveyor in ready}
        chosen = set()
        for merge_id, belt_ids in self.merge_inputs.items():
            last = self.last_merged[merge_id]
            first = belt_ids.index(last) + 1 if last is not None else 0
            for offset in range(len(belt_ids)):
                belt_id = belt_ids[(first + offset) % len(belt_ids)]
                if belt_id in ready_ids:
                    chosen.add(belt_id)
                    break
        return tuple(conveyor for conveyor in ready
                     if conveyor.config.target_id not in self.merge_inputs
                     or conveyor.config.id in chosen)

    def _apply_transfers(self, leaving: tuple[Conveyor, ...]) -> None:
        """Moves the front bag of each selected belt, exactly once.

        On the next belt the bag starts at position zero, like a newly
        admitted bag; an output unloads it automatically. A merge remembers
        which belt it let through, for the next turn. Movement is not
        repeated after the transfer: following bags use the freed space, and
        the transferred bag moves, from the next tick.
        """
        exited = []
        for conveyor in leaving:
            baggage = conveyor.baggage.pop()
            target_id = conveyor.config.target_id
            if target_id in self.merge_inputs:
                self.last_merged[target_id] = conveyor.config.id
            next_conveyor = self._next_conveyor(conveyor, baggage)
            if next_conveyor is not None:
                baggage.conveyor_id = next_conveyor.config.id
                baggage.position_m = 0.0
                next_conveyor.baggage.insert(0, baggage)
            else:
                self._exit(baggage, target_id)
                exited.append(baggage)
        self.exited_this_tick = tuple(exited)

    def _exit(self, baggage: Baggage, output_id: str) -> None:
        """Removes the bag from the plant at an output and classifies the arrival."""
        if baggage.entered_at_s is None:
            raise ValueError("An exiting bag must have been admitted")
        baggage.conveyor_id = None
        baggage.exited_at_s = self.time_s
        if baggage.destination_id == output_id:
            self.correctly_delivered_count += 1
            self.correctly_delivered_by_output[output_id] += 1
            self._recent_delivery_ticks.append(self.tick)
        else:
            # The classification of the arrival: the error was counted at the sorter.
            self.misdelivered_count += 1
            self.misdelivered_by_output[output_id] += 1
            self.events.record(self.tick, self.time_s, Severity.INFO, "wrong_exit",
                               f"Arrived at the wrong output (destination {baggage.destination_id})",
                               element_id=output_id, baggage_id=baggage.id)
        self._total_travel_time_s += self.time_s - baggage.entered_at_s

    def _forget_old_deliveries(self) -> None:
        """Drops the deliveries older than the throughput window.

        A delivery at tick t counts up to tick t + 1199: exactly 60 s.
        """
        oldest_kept = self.tick - THROUGHPUT_WINDOW_TICKS + 1
        while self._recent_delivery_ticks and self._recent_delivery_ticks[0] < oldest_kept:
            self._recent_delivery_ticks.popleft()

    def _generate(self) -> None:
        """Queues every due arrival at each input, without losing demand when it is full.

        Inputs are visited in layout order, so bag numbers are reproducible.
        The total of each input is derived from the time elapsed since its
        rate was last set (tick 0 at first), without rounding an interval to
        ticks or accumulating fractions at every step. The first arrival
        happens a full interval after that. The timestamp is that of
        the tick in which the arrival is detected (a delay shorter than one
        step). The destination is any output, drawn with equal probability.
        """
        for node in self.layout.inputs:
            since_tick, generated_before = self._rate_since[node.id]
            elapsed_ms = (self.tick - since_tick) * STEP_MS
            due_count = generated_before + int(elapsed_ms * self.arrival_rates[node.id] / 1000)
            while self.generated_by_input[node.id] < due_count:
                self.generated_by_input[node.id] += 1
                self.generated_count += 1
                self.waiting[node.id].append(Baggage(
                    id=f"bag-{self.generated_count}",
                    destination_id=self.rng.choice(self._output_ids),
                    length_m=self.layout.baggage_length_m,
                    generated_at_s=self.time_s,
                ))

    def _admit(self) -> None:
        """Admits the first waiting bag of each input whose belt entrance is free.

        The belt list is ordered from entrance to exit: the first element is
        the closest to the new bag. One admission per tick is enough because
        the new bag immediately occupies position zero. A halted belt admits
        a bag too if its entrance is free, but then keeps it there.
        """
        for input_id, queue in self.waiting.items():
            conveyor = self.input_conveyors[input_id]
            if not queue or not self._has_entry_space(conveyor, queue[0]):
                continue
            baggage = queue.popleft()
            baggage.conveyor_id = conveyor.config.id
            baggage.entered_at_s = self.time_s
            baggage.position_m = 0.0
            conveyor.baggage.insert(0, baggage)
            self.admitted_count += 1

    def _update_entrance_queues(self) -> None:
        """Records the start and end of each input's queue, not every waiting tick.

        A queue exists when at least one bag is still waiting after admission.
        It is an informational event: the prolonged-wait warning will have
        its own thresholds.
        """
        for input_id, queue in self.waiting.items():
            queued = bool(queue)
            if queued == self._entrance_queued[input_id]:
                continue
            self._entrance_queued[input_id] = queued
            if queued:
                kind, message = "entrance_queue_started", "Entrance queue: no space on the belt"
            else:
                kind, message = "entrance_queue_cleared", "Entrance queue cleared"
            self.events.record(self.tick, self.time_s, Severity.INFO, kind, message,
                               element_id=input_id)
